# DB
spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL:10}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.auto-commit=false
spring.jpa.show-sql=true

# Flyway
#  > when spring.flyway.enabled is true, FlywayAutoConfiguration works when spring-boot app starts.
spring.flyway.enabled=true
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
spring.flyway.locations=${FLYWAY_LOCATIONS:classpath:/common/db/migration,classpath:/test/db/migration}
spring.flyway.validate-on-migrate=false